# Generated by Django 3.2.15 on 2022-10-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_priceproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceproduct',
            options={'ordering': ('price',), 'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цена товаров'},
        ),
    ]
