# Generated by Django 3.2.15 on 2022-10-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_priceproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceproduct',
            options={'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цена товаров'},
        ),
    ]
